language: python
os: linux
dist: bionic
python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install poetry
    - poetry install -E travis

script:
    - flake8 fits_schema
    - poetry run python -m pytest --cov fits_schema --cov-report=xml tests/

after_success:
    - codecov
