language: python
os: linux
dist: bionic
python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install poetry
    - poetry install -E travis

script:
    - flake8 fits_schema
    - |
      poetry run python -m pytest \
      --doctest-modules \
      --cov fits_schema --cov-report=xml \
      tests fits_schema

after_success:
    - codecov
    - poetry config http-basic.pypi __token__ $PYPI_TOKEN
    - poetry build

deploy:
    provider: script
    script: poetry publish
    distributions: sdist wheel
    skip_existing: true
    cleanup: false
    on:
        tags: true
        branch: master
        condition: $TRAVIS_PYTHON_VERSION = "3.7"
